SEED = 42
MODEL_NAME = "DeepPavlov/rubert-base-cased" 
MAX_LENGTH = 256
BATCH_SIZE = 32
NUM_EPOCHS = 3
LEARNING_RATE = 2e-5
N_FOLDS = 4
DATAMAPS_EPOCHS = 7
DATAMAPS_EPOCHS_RUCOLA = 10
EASY_KEEP_RATIO = 0.7

DATASET_NAME1 = "Kostya165/ru_emotion_dvach"
DATASET_CONFIG1 = None  

DATASET_NAME2 = "RussianNLP/rucola"
DATASET_CONFIG2 = None  

DATASET_NAME3 = "RussianNLP/russian_super_glue"
DATASET_CONFIG3 = "terra"


DS2_EMBEDDING_MODEL = "BAAI/bge-m3"
DS2_NUM_CLASSES = 6
DS2_KNN_K_DETECT = 2
DS2_KNN_K_DIVERSITY = 10 
DS2_CONFIDENCE_PROB = 0.5 
DS2_HOC_MAX_STEP = 1501
DS2_HOC_LR = 0.1
DS2_HOC_NUM_ROUNDS = 50
DS2_DETECT_NUM_EPOCH = 51
DS2_EMBEDDING_BATCH_SIZE = 64
DS2_API_MAX_WORKERS = 8
DS2_API_MAX_RETRIES = 3
DS2_API_BATCH_SIZE = 512
DS2_KEEP_RATIO = 0.7

DEDUP_COSINE_THRESHOLD = 0.95
DEDUP_KNN_K = 20

VER_DEDUP_MIN_VOTES = 2

